# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3bdce6e9026a3883d357e57f043c0935"
name = "CartIQ"
handle = "cartiq"
application_url = "https://suspected-mad-compound-plains.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_customers,read_orders,read_products,write_products"

[auth]
redirect_urls = ["https://suspected-mad-compound-plains.trycloudflare.com/auth/callback", "https://suspected-mad-compound-plains.trycloudflare.com/auth/shopify/callback", "https://suspected-mad-compound-plains.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
